### ISSUE TITLE
face

### ISSUE THREAD

**Issue by pkuhxy** [PKU-YuanGroup/ConsisID#1]
https://github.com/user-attachments/assets/a70862d6-88d2-4b27-9096-261decc82080

**Comment by SHYuanBest** [comment]
![1](https://github.com/user-attachments/assets/f0e2803c-7214-4463-afd8-b28c0cd87c64)
![2](https://github.com/user-attachments/assets/3491e75c-e01a-41d3-ae01-0c2535b7fa81)
![3](https://github.com/user-attachments/assets/2ffb154f-23dc-4314-9976-95c0bd16810b)
![4](https://github.com/user-attachments/assets/9eb298a3-4c2a-407e-b73b-32f88895df22)
