### ISSUE TITLE
Out of CPU memory in gradio demo

### ISSUE THREAD

**Issue by O-O1024** [PKU-YuanGroup/ConsisID#19]
Due to GPU having only 24GB of video memory, I have to enable the option to offload the model to the CPU.
But unfortunately, the CPU only has 43GB of memory, frame interpolation and later operations consumes a lot of memory, which resulting in OOM.

**Comment by SHYuanBest** [comment]
Thanks for your interest. You have to turn on the following lines if you don't have multiple GPUs or enough GPU memory(such as H100), but  it will cost more time in inference and may also reduce the quality.
```
pipe.enable_model_cpu_offload()
pipe.enable_sequential_cpu_offload()
pipe.vae.enable_slicing()
pipe.vae.enable_tiling()
```

**Comment by O-O1024** [comment]
I change to use ComfyUI instead.

**Comment by O-O1024** [comment]
I change to use ComfyUI instead .
