### ISSUE TITLE
All attempts failed for image 0. No valid embeddings could be generated.

### ISSUE THREAD

**Issue by Strive21** [PKU-YuanGroup/ConsisID#24]
UnboundLocalError: cannot access local variable 'video_latents' where it is not associated with a value. This error occurs in train.py line 1123. And process_face_embeddings() doesn't have the argument “cal_uncond”.

**Comment by SHYuanBest** [comment]
thanks for your report, i am reorganizing the code and integrating `ConsisID` into `diffusers`, and will fix this bug very soon.

**Comment by SHYuanBest** [comment]
I have fix the error about `train.py`.

**Comment by JachinJiang** [comment]
hi, I didn’t find train.py in hg, and I encountered the same problem All attempts failed for image 0. No valid embeddings could be generated. using the code in this repository

**Comment by SHYuanBest** [comment]
redirect to https://github.com/PKU-YuanGroup/ConsisID/issues/46
